# Written by Sara Knox
# March 2024

# Dec 17, 2024 (Zoran)
#    - Added northOffset: 0 based on ghg Metadata.

Metadata:
  siteID: YOUNG
  estYear: 2021
  lat: 50.3623
  long: -100.20242
  TimeZoneHour: -6
  northOffset: 0
  
  