# Written by June Skeeter
# March 2024

Metadata:
  siteID: BB2
  estYear: 2019 
  lat: 49.1190
  long: -122.9947
  TimeZoneHour: -8
  northOffset: 180
Processing:
  ThirdStage:
    RF_GapFilling:
      Run: False
