Database:
  Paths:
    SecondStage: Clean/SecondStage
    ThirdStage: Clean/ThirdStage
    FirstStage:
      Met:
        raw: Met
        clean: Met/clean
      Flux:
        raw: Flux
        clean: Flux/clean
      Manual: 
        raw: Met/Manual
        clean: Met/clean
      ECCC:
        # Station IDs see: _ECCC_Station_List.csv
        raw: ECCC/STN_ID
        clean: Met/clean
  Timestamp: 
    name: clean_tv
    dtype: float64
    precision: 8
    base: 719529
    base_unit: D
  Traces:
    dtype: float32
    precision: 4
Shortcuts:
  # These can be replace with local paths
  datadump: X:/SITEID/
  highfreq: C:/highfreq/SITEID/
  eddypro_outputs: \\vinimet.geog.ubc.ca\EddyPro_Output$/SITEID/
  sites: C:/temp/
