Database:
  Paths:
    SecondStage: Clean/SecondStage
    ThirdStage: Clean/ThirdStage
    ThirdStage_Default: Clean/ThirdStage_Default_Ustar
    ThirdStage_Advanced: Clean/ThirdStage_Full_Ustar_Uncertainty
    FirstStage:
      Met:
        raw: Met
        clean: Met/clean
      Flux:
        raw: Flux
        clean: Flux/clean
      Manual: 
        raw: Met/Manual
        clean: Met/clean
      ECCC:
        # Station IDs see: _ECCC_Station_List.csv
        raw: ECCC/STN_ID
        clean: Met/clean
  Timestamp: 
    name: clean_tv
    dtype: float64
    precision: 8
    base: 719529
    base_unit: D
  Traces:
    dtype: float32
    precision: 4
Processing:
  ThirdStage:
    Storage_Terms:
      # Will be named acceding to the key, calculated as the sum of the nested key/value pair
      NEE:
        FC: SC
      FCH4_SC:
        FCH4: SCH4
      H_SC:
        H: SH
      LE_SC:
        LE: SLE
    REddyProc:
      do_REddyProc: 1
      Ustar_filtering:
        # Keep "run_defaults" as True to run "fast" ustar filtering
        # U05, U50, U95
        run_defaults: True
        default_uncertainty:
          samples: 100
          min: 0.05
          max: 0.095
          steps: 3 
        # If run_defaults != True, conduct "full_uncertainty" 
        # EProc$sEstimateUstarScenarios(nSample = samples, probs = seq(min_quantile,max_quantile,length.out = steps))
        # See Appendix B5 Wutzler (2018)
        full_uncertainty:
          samples: 200
          min: 0.025
          max: 0.0975
          steps: 39 
      vars_in:
        # Variables to feed to REddyProc (from second stage)
        # Key is REddyProc name, val is database name 
        # year,doy,and HHMM are autogenerated in script)
        # Any variable listed here 
        NEE: NEE
        LE: LE_SC
        H: H_SC
        FCH4: FCH4_SC
        Rg: SW_IN_1_1_1
        Tair: TA_1_1_1
        rH: RH_1_1_1
        VPD: VPD_1_1_1
        Ustar: USTAR
      # MDS gap filling (will only fill these variables *if* present in "vars_in")
      MDSGapFill:
        UStarScens: NEE,LE,H,FCH4
        basic: Rg,Tair,rH,VPD

    RF_GapFilling:
      do_REddyProc: 1
      # Example showing how configuration could be setup.  Not ideal set of inputs
      # Lots of pending optimizations to be made to RF approach 
      # Example set of predictors (not optimized!!!!!!!) 
      # Variables with an _f at the end have been gapfilled using MDS in REddyProc
      # Could expand to do MDS gap filling on all necessary inputs ...
      # Or work out our own gap-filling procedures for met/sub surface variables

      # Name of variable to be filled (not including REddyProc qualifier)
      # When saved as the model output, the variable will be appended with a tag
      # e.g., FCH4_SC_RF_f (gap filled w/ random forest) and FCH4_SC_RF_fall (modelled w/ random forest)
      FCH4_SC:
        # Full name of the Ustar filtered ReddyProc Variable (cleanest trace) to train model
        var_dep: FCH4_SC_U50_orig
        Predictors: TA_1_1_1_f,TS_1_1_1,TS_1_2_1,TS_1_3_1,WTD_1,RH_1_1_1_f,VPD_1_1_1_f,PA_1_1_1

      NEE:
        # Fill the ReddyProc UStar Filtered Variable
        var_dep: NEE_U50_orig
        Predictors: TA_1_1_1_f,TS_1_1_1,TS_1_2_1,TS_1_3_1,WTD_1,RH_1_1_1_f,VPD_1_1_1_f,PA_1_1_1

      H_SC:
        # Fill the ReddyProc UStar Filtered Variable
        var_dep: H_SC_U50_orig
        Predictors: TA_1_1_1_f,TS_1_1_1,TS_1_2_1,TS_1_3_1,WTD_1,RH_1_1_1_f,VPD_1_1_1_f,PA_1_1_1

      LE_SC:
        # Fill the ReddyProc UStar Filtered Variable
        var_dep: LE_SC_U50_orig
        Predictors: TA_1_1_1_f,TS_1_1_1,TS_1_2_1,TS_1_3_1,WTD_1,RH_1_1_1_f,VPD_1_1_1_f,PA_1_1_1

    Final_Outputs:
      # Copy and rename final outputs for base third stage folder
      # Just an example syntax, not a complete list
      # Final third stage name is key, intermediary third stage name is value
      TA_1_1_1: TA_1_1_1_f
      RH_1_1_1: RH_1_1_1_f
      NEE: NEE_U50_f
      FCH4_FC: FCH4_SC_RF_f





# Shortcuts:
#   # These can be replace with local paths
#   datadump: X:/SITEID/
#   highfreq: C:/highfreq/SITEID/
#   eddypro_outputs: \\vinimet.geog.ubc.ca\EddyPro_Output$/SITEID/
#   sites: C:/temp/
