Database:
  Paths:
    SecondStage: Clean/SecondStage
    ThirdStage: Clean/ThirdStage
    FirstStage:
      Met:
        raw: Met
        clean: Met/clean
      Flux:
        raw: Flux
        clean: Flux/clean
      Manual: 
        raw: Met/Manual
        clean: Met/clean
      ECCC:
        # Station IDs see: _ECCC_Station_List.csv
        raw: ECCC/STN_ID
        clean: Met/clean
  Timestamp: 
    name: clean_tv
    dtype: float64
    precision: 8
    base: 719529
    base_unit: D
  Traces:
    dtype: float32
    precision: 4
Processing:
  ThirdStage:
    Storage_Terms:
      # Will be named acceding to the key, calculated as the sum of the nested key/value pair
      NEE:
        FC: SC
      FCH4_SC:
        FCH4: SCH4
      H_SC:
        H: SH
      LE_SC:
        LE: SLE
    REddyProc:
      do_REddyProc: 1
      Ustar_filtering:
        # Keep as True to run "fast"
        run_defaults: True
        # If run_defaults != True, conduct "full" run (e.g., see bellow)
        # EProc$sEstimateUstarScenarios(nSample = samples, probs = seq(min_quantile,max_quantile,length.out = steps))
        # See Appendix B5 Wutzler (2018)
        samples: 200
        min: 0.025
        max: 0.095
        steps: 39 
      vars_in:
        # Variables to feed to REddyProc (from second stage)
        # Key is REddyProc name, val is database name 
        # year,doy,and HHMM are autogenerated in script)
        # Any variable listed here 
        NEE: NEE
        LE: LE_SC
        H: H_SC
        FCH4: FCH4_SC
        Rg: SW_IN_1_1_1
        Tair: TA_1_1_1
        rH: RH_1_1_1
        VPD: VPD_1_1_1
        Ustar: USTAR
      # MDS gap filling (will only fill these variables *if* present in "vars_in")
      MDSGapFill:
        UStarScens: NEE,LE,H,FCH4
        basic: Rg,Tair,rH,VPD

    RF_GapFilling:
      # Example showing how configuration could be setup.  Not ideal set of inputs
      # Lots of pending optimizations to be made to RF approach 
      # Example set of predictors (not optimized!!!!!!!) 
      # Variables with an _f at the end have been gapfilled using MDS in REddyProc
      # Could expand to do MDS gap filling on all necessary inputs ...
      # Or work out our own gap-filling procedures for met/sub surface variables
      FCH4_SC:
        # Fill the ReddyProc UStar Filtered Variable
        var_dep: FCH4_SC_U50_orig
        Predictors: TA_1_1_1_f,TS_1_1_1,TS_1_2_1,TS_1_3_1,WTD_1,RH_1_1_1_f,VPD_1_1_1_f,PA_1_1_1

      NEE:
        # Fill the ReddyProc UStar Filtered Variable
        var_dep: NEE_U50_orig
        Predictors: TA_1_1_1_f,TS_1_1_1,TS_1_2_1,TS_1_3_1,WTD_1,RH_1_1_1_f,VPD_1_1_1_f,PA_1_1_1

      # H_SC:
      #   # Fill the ReddyProc UStar Filtered Variable
      #   var_dep: H_SC_U50_orig
      #   Predictors: TA_1_1_1_f,TS_1_1_1,TS_1_2_1,TS_1_3_1,WTD_1,RH_1_1_1_f,VPD_1_1_1_f,PA_1_1_1

      # LE_SC:
      #   # Fill the ReddyProc UStar Filtered Variable
      #   var_dep: LE_SC_U50_orig
      #   Predictors: TA_1_1_1_f,TS_1_1_1,TS_1_2_1,TS_1_3_1,WTD_1,RH_1_1_1_f,VPD_1_1_1_f,PA_1_1_1







# Shortcuts:
#   # These can be replace with local paths
#   datadump: X:/SITEID/
#   highfreq: C:/highfreq/SITEID/
#   eddypro_outputs: \\vinimet.geog.ubc.ca\EddyPro_Output$/SITEID/
#   sites: C:/temp/
