# Written by Sara Knox (edited by Zoran Nesic)
# March 2024

# Dec 17, 2024 (Zoran)
#    - Added northOffset: 0 based on ghg Metadata.

Metadata:
  siteID: OHM
  estYear: 2021
  lat: 50.174
  long: -97.123
  TimeZoneHour: -6
  northOffset: 0

