# Written by June Skeeter
# March 2024

Metadata:
  siteID: BBS
  estYear: 2023 
  lat: 49.12930679
  long: -122.9849701
  TimeZoneHour: -8

Processing:
  ThirdStage:
    REddyProc:
      vars_in:
        # Define a custom input variable
        seasons: Season
