# Written by June Skeeter (edited by Zoran)
# May 2024

# Dec 17, 2024 (Zoran)
#    - Added northOffset: 180 based on ghg Metadata.

Metadata:
  siteID: RBM
  estYear: 2022 
  lat: 49.131253
  long: -123.196366
  TimeZoneHour: -8
  northOffset: 180



